---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: foundryos-2
description: customised Fedora Kinoite image for my own personal use

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      nonfree: rpmfusion
    install:
      packages:
        - discord

  - type: dnf
    repos:
      cleanup: true
      nonfree: negativo17
    install:
      packages:
        - steam
        - ffmpeg
        - yt-dlp
        - virt-manager
        - kcalc
        - kolourpaint
        - soundkonverter
    replace:
      - from-repo: updates
        packages:
          - old: sddm
            new: plasma-login-manager
        allow-erasing: true

  - type: dnf
    install:
      packages:
        - https://github.com/patryk-ku/music-discord-rpc/releases/latest/download/music-discord-rpc.rpm

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.kde.haruna
          - org.kde.kasts
          - org.atheme.audacious
          - org.fedoraproject.MediaWriter
      - scope: user

  - type: signing
